### ISSUE TITLE
Documentation Needs to be Updated

### ISSUE THREAD

**Issue by osumac24** [yalochat/hapi-kafka-plugin#3]
The readme says to use server.plugins.kafka.producer() but I get the error **server.plugins.kafka.producer is not a function**.  I was, however, able to get produce messages by using server.plugins.kafka.producer.produce().
```
server.plugins.kafka.producer.produce(
    'topic',
    null,
    Buffer.from('hello world'),
    null,
    Date.now(),
 )
```

**Comment by yoelfme** [comment]
Hello @osumac24, thanks for found it, I will fix the README.md  ASAP.

Regards
